import '../../models/chat_model.dart';
import '../../models/dealer_model.dart';
import '../../models/notification_model.dart';
import '../../models/vehicle_model.dart';

/// Static mock data used when [ApiConstants.useMockData] is true.
class VehicleRepository {
  VehicleRepository._();

  static const List<DealerModel> mockDealers = [
    DealerModel(
      id: "1",
      name: "AutoPrime Motors",
      logo: "assets/images/dealers/dealer1.png",
      rating: 4.8,
      totalCars: 47,
      location: "Banjara Hills, Hyderabad",
      isVerified: true,
    ),
    DealerModel(
      id: "2",
      name: "Prestige Auto Hub",
      logo: "assets/images/dealers/dealer2.png",
      rating: 4.6,
      totalCars: 63,
      location: "Kondapur, Hyderabad",
      isVerified: true,
    ),
    DealerModel(
      id: "3",
      name: "Elite Cars",
      logo: "assets/images/dealers/dealer3.png",
      rating: 4.7,
      totalCars: 35,
      location: "Madhapur, Hyderabad",
      isVerified: false,
    ),
  ];

  static final List<ChatSummary> mockChats = [
    ChatSummary(
      id: 'mock-chat-1',
      otherUser: const ChatUser(id: 'seller-1', name: 'Rajesh Nair', avatar: 'assets/images/avatars/profile.png'),
      lastMessage: ChatMessage(
        id: '1',
        content: "Hi, is the Swift still available?",
        senderId: 'me',
        createdAt: DateTime(2026, 7, 30, 14, 30),
      ),
      updatedAt: DateTime(2026, 7, 30, 14, 30),
    ),
    ChatSummary(
      id: 'mock-chat-2',
      otherUser: const ChatUser(id: 'seller-2', name: 'Priya Menon', avatar: 'assets/images/avatars/profile.png'),
      lastMessage: ChatMessage(
        id: '2',
        content: "Yes, you can visit tomorrow for a test drive.",
        senderId: 'seller-2',
        createdAt: DateTime(2026, 7, 29, 10, 15),
      ),
      updatedAt: DateTime(2026, 7, 29, 10, 15),
    ),
  ];

  static final Map<String, List<ChatMessage>> mockMessages = {
    'mock-chat-1': [
      ChatMessage(
        id: '1',
        content: "Hi, is the Swift still available?",
        senderId: 'me',
        createdAt: DateTime(2026, 7, 30, 14, 0),
      ),
      ChatMessage(
        id: '2',
        content: "Yes it is! Would you like to schedule a visit?",
        senderId: 'seller-1',
        createdAt: DateTime(2026, 7, 30, 14, 15),
      ),
      ChatMessage(
        id: '3',
        content: "Great, I'll come this Saturday.",
        senderId: 'me',
        createdAt: DateTime(2026, 7, 30, 14, 30),
      ),
    ],
  };

  static final List<NotificationModel> mockNotifications = [
    NotificationModel(
      id: 'n1',
      type: 'message',
      title: 'Rajesh Nair',
      body: 'Yes it is! Would you like to schedule a visit?',
      createdAt: DateTime(2026, 7, 30, 14, 15),
      relatedChatId: 'mock-chat-1',
    ),
    NotificationModel(
      id: 'n2',
      type: 'price_drop',
      title: 'Price drop',
      body: 'Maruti Swift VXI is now ₹4.6L (was ₹4.8L)',
      createdAt: DateTime(2026, 7, 29, 9, 0),
      relatedVehicleId: '1',
    ),
    NotificationModel(
      id: 'n3',
      type: 'callback',
      title: 'Callback requested',
      body: 'A buyer wants a callback about your Maruti Suzuki Brezza',
      createdAt: DateTime(2026, 7, 27, 18, 30),
      read: true,
    ),
  ];

  static const List<VehicleModel> all = [
    VehicleModel(
      id: "1",
      name: "Maruti Swift VXI",
      category: "Cars",
      images: ["assets/images/cars/car1.png", "assets/images/cars/car2.png"],
      price: "₹4.8L",
      originalPrice: "₹5.5L",
      discountPercent: 12,
      isFeatured: true,
      rating: 4.3,
      fuelType: "Petrol",
      transmission: "Manual",
      year: "2021",
      seats: "5",
      kmDriven: "28.4k km",
      owners: "1 Owner",
      condition: "Good",
      insurance: "Valid",
      rcStatus: "Clear",
      soldCount: "1.2k+",
      description:
          "The Maruti Swift VXI is a 2021 model in excellent condition with only 28.4k km driven. Features include Petrol engine, Manual transmission, and comes with a clear RC and valid insurance.",
      location: "Banjara Hills, Hyderabad",
      dealerId: "1",
      dealerName: "AutoPrime Motors",
      sellerName: "Rajesh Nair",
      sellerPhone: "+919876543210",
      sellerAvatar: "assets/images/avatars/profile.png",
      dealerVerified: true,
    ),
    VehicleModel(
      id: "2",
      name: "Honda Activa 6G",
      category: "Scooters",
      images: ["assets/images/cars/scooter1.png"],
      price: "₹72K",
      originalPrice: "₹85K",
      discountPercent: 15,
      rating: 4.5,
      fuelType: "Petrol",
      transmission: "Automatic",
      year: "2022",
      seats: "2",
      kmDriven: "11.2k km",
      owners: "1 Owner",
      condition: "Excellent",
      insurance: "Valid",
      rcStatus: "Clear",
      soldCount: "640+",
      description:
          "Honda Activa 6G, well maintained with single owner. Ideal daily commuter with excellent mileage.",
      location: "Kondapur, Hyderabad",
      dealerId: "2",
      dealerName: "Prestige Auto Hub",
      sellerName: "Priya Menon",
      sellerPhone: "+919123456780",
      sellerAvatar: "assets/images/avatars/profile.png",
      dealerVerified: true,
    ),
    VehicleModel(
      id: "3",
      name: "Tata Nexon EV Max",
      category: "Cars",
      images: ["assets/images/cars/car3.png"],
      price: "₹14.5L",
      originalPrice: "₹16.8L",
      discountPercent: 13,
      isFeatured: true,
      rating: 4.6,
      fuelType: "Electric",
      transmission: "Automatic",
      year: "2023",
      seats: "5",
      kmDriven: "9.8k km",
      owners: "1 Owner",
      condition: "Excellent",
      insurance: "Valid",
      rcStatus: "Clear",
      soldCount: "310+",
      description:
          "Tata Nexon EV Max with long range battery, barely used, comes with home charger.",
      location: "Gachibowli, Hyderabad",
      dealerId: "1",
      dealerName: "AutoPrime Motors",
      sellerName: "Rajesh Nair",
      sellerPhone: "+919876543210",
      sellerAvatar: "assets/images/avatars/profile.png",
      dealerVerified: true,
    ),
    VehicleModel(
      id: "4",
      name: "Royal Enfield Meteor 350",
      category: "Bikes",
      images: ["assets/images/cars/bike1.png"],
      price: "₹1.7L",
      originalPrice: "₹1.9L",
      discountPercent: 14,
      rating: 4.4,
      fuelType: "Petrol",
      transmission: "Manual",
      year: "2021",
      seats: "2",
      kmDriven: "18.7k km",
      owners: "1 Owner",
      condition: "Good",
      insurance: "Valid",
      rcStatus: "Clear",
      soldCount: "420+",
      description:
          "Royal Enfield Meteor 350 in great shape, recently serviced, single owner.",
      location: "Madhapur, Hyderabad",
      dealerId: "3",
      dealerName: "Elite Cars",
      sellerName: "Arjun Rao",
      sellerPhone: "+919000011122",
      sellerAvatar: "assets/images/avatars/profile.png",
      dealerVerified: false,
    ),
    VehicleModel(
      id: "5",
      name: "Hyundai Creta SX",
      category: "Cars",
      images: ["assets/images/cars/car4.png"],
      price: "₹11.8L",
      originalPrice: "₹13.4L",
      discountPercent: 12,
      isFeatured: true,
      rating: 4.5,
      fuelType: "Diesel",
      transmission: "Automatic",
      year: "2022",
      seats: "5",
      kmDriven: "22.1k km",
      owners: "1 Owner",
      condition: "Excellent",
      insurance: "Valid",
      rcStatus: "Clear",
      soldCount: "560+",
      description:
          "Hyundai Creta SX top variant, sunroof, well maintained with complete service history.",
      location: "Jubilee Hills, Hyderabad",
      dealerId: "2",
      dealerName: "Prestige Auto Hub",
      sellerName: "Priya Menon",
      sellerPhone: "+919123456780",
      sellerAvatar: "assets/images/avatars/profile.png",
      dealerVerified: true,
    ),
    VehicleModel(
      id: "6",
      name: "Bajaj Pulsar NS200",
      category: "Bikes",
      images: ["assets/images/cars/bike2.png"],
      price: "₹98K",
      originalPrice: "₹1.1L",
      discountPercent: 15,
      rating: 4.2,
      fuelType: "Petrol",
      transmission: "Manual",
      year: "2020",
      seats: "2",
      kmDriven: "31.5k km",
      owners: "2 Owners",
      condition: "Good",
      insurance: "Expired",
      rcStatus: "Clear",
      soldCount: "280+",
      description:
          "Bajaj Pulsar NS200, sporty and fun to ride, minor cosmetic wear, mechanically sound.",
      location: "Kukatpally, Hyderabad",
      dealerId: "3",
      dealerName: "Elite Cars",
      sellerName: "Arjun Rao",
      sellerPhone: "+919000011122",
      sellerAvatar: "assets/images/avatars/profile.png",
      dealerVerified: false,
    ),
  ];

  static VehicleModel? byId(String id) {
    for (final v in all) {
      if (v.id == id) return v;
    }
    return null;
  }
}